version: "3.9"

services:
 
  Api_Tarea:
    container_name: api_tarea
    image: api_tarea:1.0.0 
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:mysql://java_db:3306/api_tarea?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
      - DB_USER_NAME=root
      - DB_PASSWORD=prueba 
    restart: always  
    depends_on:
      - java_db
      
  java_db:
    container_name: java_db
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: clinica_veterinaria
    restart: always